run:
  timeout: 5m

linter-settings:
  lll:
    line-length: 200

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - revive # replacement for golint
    - gofmt
    - goimports
    # - unused # Go1.18 disable
    - varcheck
    - deadcode
    - misspell
    - typecheck
    # - structcheck # Go1.18 disable
    # - staticcheck # Go1.18 disable
    # - gosimple # Go1.18 disable
    - gosec